### ISSUE TITLE
allow option to disable rendering for code that's ran by unit testers.

### ISSUE THREAD

**Issue by bonesoul** [Mpdreamz/shellprogressbar#69]
right now with in my unit tests getting invalid handle error;

```
"System.IO.IOException: The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_CursorTop()
   at ShellProgressBar.ProgressBar..ctor(Int32 maxTicks, String message, ProgressBarOptions options)
```

**Comment by LevYas** [comment]
I had exactly the same problem. As a quick fix, I used a "proxy" pattern:

    public sealed class ProgressBarProxy : IDisposable
    {
        private readonly ProgressBar? _progressBar;

        public ProgressBarProxy(int maxTicks, string message)
            => _progressBar = Console.IsOutputRedirected ? null : new ProgressBar(maxTicks, message);

        public void Tick(string? message = null) => _progressBar?.Tick(message);
        public void Dispose() => _progressBar?.Dispose();
    }

But it would be nice if that check will be inside the constructor.

**Comment by mrwensveen** [comment]
Maybe you could implement/mock IProgressBar and use dependency injection in parts that will be unit tested?
